global:
  namespace: "with-vault-app-dev"
# Database Configuration
postgresql:
  enabled: true
  name: postgres
  image: registry.redhat.io/rhel9/postgresql-15:latest
  database: appdb
  username: appuser
  # password: "XXXXXXXXXXXXXXXXXXXXX!" # In production, pull from Vault or SealedSecret
  storageSize: 5Gi
  port: 5432
  storageClassName: ocs-storagecluster-ceph-rbd
# Backend API Configuration
backend:
  name: backend-api
  replicas: 2
  port: 8080
  image:
    repository: "image-registry.openshift-image-registry.svc:5000/with-vault-app-dev/backend-api"
    tag: "8ab71a6b231a964ada1d2e83672e771441f99f5a"
  git:
    uri: "https://github.com/sksinghsujit/3tier-app-backend-service-with-vault.git"
    ref: "main"
    contextDir: "/"
  env:
    DB_HOST: "postgres"
    DB_PORT: "5432"
    DB_NAME: "appdb"
    DB_USER: "appuser"
# Frontend Web App Configuration
frontend:
  name: frontend-web
  replicas: 2
  port: 8080
  image:
    repository: "image-registry.openshift-image-registry.svc:5000/with-vault-app-dev/frontend-web"
    tag: "595730297fd0341bede5880a33e292dba1e1339a"
  git:
    uri: "https://github.com/sksinghsujit/3tier-app-frontend-service-with-vault.git"
    ref: "main"
    contextDir: "/"
  route:
    enabled: true
    host: "with-vault-app-dev.apps.c1.ucmc.org" # Replace with your cluster domain
    tls:
      termination: edge
vault:
  address: "http://vault1.ucmcswg.com:8200"
  connectionName: "vault-connection"
  authName: "vault-auth"
  role: "with-vault-dev-app-role"
  serviceAccount: "default"
  kubernetesAuthMount: "kubernetes"
  kvMount: "secret"
  refreshInterval: "1m"
  secrets:
    databasePath: "dev/database"
    githubPath: "dev/github"
    sonarqubePath: "dev/sonarqube"
