apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: DB_HOST
              value: {{ .Values.backend.env.DB_HOST }}
            - name: DB_PORT
              value: {{ .Values.backend.env.DB_PORT | quote }}
            - name: DB_NAME
              value: {{ .Values.backend.env.DB_NAME }}
            - name: DB_USER
              value: {{ .Values.backend.env.DB_USER }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.name }}-secret
                  key: POSTGRESQL_PASSWORD