apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  selector:
    app: {{ .Values.frontend.name }}