apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgresql.name }}
spec:
  serviceName: {{ .Values.postgresql.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgresql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresql.name }}
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: {{ .Values.postgresql.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.postgresql.name }}-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.postgresql.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.postgresql.storageSize }}