apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: {{ .Values.vault.connectionName | default "vault-connection" }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  address: {{ .Values.vault.address | quote }}
  skipTLSVerify: true
